//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;



/// <summary>
///   A strongly-typed resource class, for looking up localized strings, etc.
/// </summary>
// This class was auto-generated by the StronglyTypedResourceBuilder
// class via a tool like ResGen or Visual Studio.
// To add or remove a member, edit your .ResX file then rerun ResGen
// with the /str option, or rebuild your VS project.
[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
internal class en_US {
    
    private static global::System.Resources.ResourceManager resourceMan;
    
    private static global::System.Globalization.CultureInfo resourceCulture;
    
    [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
    internal en_US() {
    }
    
    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Resources.ResourceManager ResourceManager {
        get {
            if (object.ReferenceEquals(resourceMan, null)) {
                global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("checker.en-US", typeof(en_US).Assembly);
                resourceMan = temp;
            }
            return resourceMan;
        }
    }
    
    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    internal static global::System.Globalization.CultureInfo Culture {
        get {
            return resourceCulture;
        }
        set {
            resourceCulture = value;
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Battery Breached Parameter .
    /// </summary>
    internal static string BreachMessage {
        get {
            return ResourceManager.GetString("BreachMessage", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Please provide charge rate value.
    /// </summary>
    internal static string ChargeRateValue {
        get {
            return ResourceManager.GetString("ChargeRateValue", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Charge Rate.
    /// </summary>
    internal static string CR {
        get {
            return ResourceManager.GetString("CR", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The charge rate is high compared to the maximum limits.
    /// </summary>
    internal static string High_ChargeRate {
        get {
            return ResourceManager.GetString("High_ChargeRate", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The state of charge is high compared to the maximum limits.
    /// </summary>
    internal static string High_Soc {
        get {
            return ResourceManager.GetString("High_Soc", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The temperature is high compared to the maximum limits.
    /// </summary>
    internal static string High_Temperature {
        get {
            return ResourceManager.GetString("High_Temperature", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The state of charge is low compared to the minimum limits.
    /// </summary>
    internal static string Low_Soc {
        get {
            return ResourceManager.GetString("Low_Soc", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to The temperature is low compared to the minimum limits.
    /// </summary>
    internal static string Low_Temperature {
        get {
            return ResourceManager.GetString("Low_Temperature", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Charge Rate is Normal.
    /// </summary>
    internal static string Normal_ChargeRate {
        get {
            return ResourceManager.GetString("Normal_ChargeRate", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to State of Charge is Normal.
    /// </summary>
    internal static string Normal_Soc {
        get {
            return ResourceManager.GetString("Normal_Soc", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Temperature is Normal.
    /// </summary>
    internal static string Normal_Temperature {
        get {
            return ResourceManager.GetString("Normal_Temperature", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to State Of Charge.
    /// </summary>
    internal static string SOC {
        get {
            return ResourceManager.GetString("SOC", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Please provide state of charge value.
    /// </summary>
    internal static string StateOfChargeValue {
        get {
            return ResourceManager.GetString("StateOfChargeValue", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Temperature.
    /// </summary>
    internal static string Temp {
        get {
            return ResourceManager.GetString("Temp", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Please provide temperature unit 1.Celsius 2.Fahrenheit.
    /// </summary>
    internal static string TemperatureUnit {
        get {
            return ResourceManager.GetString("TemperatureUnit", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Please provide temperature value.
    /// </summary>
    internal static string TemperatureValue {
        get {
            return ResourceManager.GetString("TemperatureValue", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Warning! Charge rate is heading towards maximum limit value.
    /// </summary>
    internal static string Warning_ChargeRate_High {
        get {
            return ResourceManager.GetString("Warning_ChargeRate_High", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Warning! State of charge is heading towards maximum limit value.
    /// </summary>
    internal static string Warning_Soc_High {
        get {
            return ResourceManager.GetString("Warning_Soc_High", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Warning! State of charge is heading towards minimum limit value.
    /// </summary>
    internal static string Warning_Soc_Low {
        get {
            return ResourceManager.GetString("Warning_Soc_Low", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Warning! Temperature is heading towards maximum limit value.
    /// </summary>
    internal static string Warning_Temperature_High {
        get {
            return ResourceManager.GetString("Warning_Temperature_High", resourceCulture);
        }
    }
    
    /// <summary>
    ///   Looks up a localized string similar to Warning! Temperature is heading towards minimum limit value.
    /// </summary>
    internal static string Warning_Temperature_Low {
        get {
            return ResourceManager.GetString("Warning_Temperature_Low", resourceCulture);
        }
    }
}
